Fixed some errors
vidify/vidify.org-source pull request #31
Opened 2020-09-26 18:34 UTC by MixedDrinks

2020-09-27 21:00 UTC, marioortizmanero requested changes
Left a few notes before merging. Please for the next time don't change stuff that is unrelated to the PR, like moving files into `es`, `en`... directories because it makes it hard to read the diffs afterwards. You can just do multiple PRs to make it more clean. Don't worry about it in this case though.

2020-09-27 21:00 UTC, marioortizmanero commented on config.toml
> +description = "123"
This is missing and it's fairly important. Can you edit this section before I merge?

2020-09-27 21:00 UTC, marioortizmanero commented on data/en/apis.yml
> +
unnecessary whitespace

2020-09-27 21:00 UTC, marioortizmanero commented on data/en/service.yml
> +
unnecessary change

2020-09-28 11:31 UTC, MixedDrinks commented on config.toml
> +description = "123"
OK

2020-09-28 11:31 UTC, closed without merging